repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        name: ruff lint
      - id: ruff-format
        name: ruff format

  - repo: local
    hooks:
      - id: ty-check
        name: ty type check
        entry: uvx ty check
        language: system
        types: [python]
        pass_filenames: false

